/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

/**
 *  Generic path-based filter class.
 */
public class BasePathFilter extends IntVarLocalSearchFilter {
  private transient long swigCPtr;

  protected BasePathFilter(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.BasePathFilter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BasePathFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_BasePathFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean accept(Assignment delta, Assignment deltadelta, long objective_min, long objective_max) {
    return mainJNI.BasePathFilter_accept(swigCPtr, this, Assignment.getCPtr(delta), delta, Assignment.getCPtr(deltadelta), deltadelta, objective_min, objective_max);
  }

  public void onSynchronize(Assignment delta) {
    mainJNI.BasePathFilter_onSynchronize(swigCPtr, this, Assignment.getCPtr(delta), delta);
  }

}
