/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

/**
 *  GlobalVehicleBreaksConstraint ensures breaks constraints are enforced on all vehicles in the dimension passed to its constructor. It is intended to be used for dimensions representing time. A break constraint ensures break intervals fit on the route of a vehicle. For a given vehicle, it forces break intervals to be disjoint from visit intervals, where visit intervals start at CumulVar(node) and last for node_visit_transit[node]. Moreover, it ensures that there is enough time between two consecutive nodes of a route to do transit and vehicle breaks, i.e. if Next(nodeA) = nodeB, CumulVar(nodeA) = tA and CumulVar(nodeB) = tB, then SlackVar(nodeA) &gt;= sum_{breaks [tA, tB)} duration(break).
 */
public class GlobalVehicleBreaksConstraint extends Constraint {
  private transient long swigCPtr;

  protected GlobalVehicleBreaksConstraint(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.GlobalVehicleBreaksConstraint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GlobalVehicleBreaksConstraint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_GlobalVehicleBreaksConstraint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GlobalVehicleBreaksConstraint(RoutingDimension dimension) {
    this(mainJNI.new_GlobalVehicleBreaksConstraint(RoutingDimension.getCPtr(dimension), dimension), true);
  }

  public String toString() {
    return mainJNI.GlobalVehicleBreaksConstraint_toString(swigCPtr, this);
  }

  public void post() {
    mainJNI.GlobalVehicleBreaksConstraint_post(swigCPtr, this);
  }

  public void initialPropagate() {
    mainJNI.GlobalVehicleBreaksConstraint_initialPropagate(swigCPtr, this);
  }

}
