/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class IntVarLocalSearchHandler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntVarLocalSearchHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVarLocalSearchHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_IntVarLocalSearchHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntVarLocalSearchHandler() {
    this(mainJNI.new_IntVarLocalSearchHandler__SWIG_0(), true);
  }

  public IntVarLocalSearchHandler(IntVarLocalSearchHandler other) {
    this(mainJNI.new_IntVarLocalSearchHandler__SWIG_1(IntVarLocalSearchHandler.getCPtr(other), other), true);
  }

  public IntVarLocalSearchHandler(IntVarLocalSearchOperator op) {
    this(mainJNI.new_IntVarLocalSearchHandler__SWIG_2(IntVarLocalSearchOperator.getCPtr(op), op), true);
  }

  public boolean valueFromAssignment(Assignment assignment, IntVar var, long index, long[] value) {
    return mainJNI.IntVarLocalSearchHandler_valueFromAssignment(swigCPtr, this, Assignment.getCPtr(assignment), assignment, IntVar.getCPtr(var), var, index, value);
  }

  public void onRevertChanges(long index, long value) {
    mainJNI.IntVarLocalSearchHandler_onRevertChanges(swigCPtr, this, index, value);
  }

  public void onAddVars() {
    mainJNI.IntVarLocalSearchHandler_onAddVars(swigCPtr, this);
  }

}
