/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public interface mainConstants {
  // VarTypes 
  /**
   *  This enum is used internally to do dynamic typing on subclasses of integer variables.
   */

  public final static int UNSPECIFIED = mainJNI.UNSPECIFIED_get();
  public final static int DOMAIN_INT_VAR = mainJNI.DOMAIN_INT_VAR_get();
  public final static int BOOLEAN_VAR = mainJNI.BOOLEAN_VAR_get();
  public final static int CONST_VAR = mainJNI.CONST_VAR_get();
  public final static int VAR_ADD_CST = mainJNI.VAR_ADD_CST_get();
  public final static int VAR_TIMES_CST = mainJNI.VAR_TIMES_CST_get();
  public final static int CST_SUB_VAR = mainJNI.CST_SUB_VAR_get();
  public final static int OPP_VAR = mainJNI.OPP_VAR_get();
  public final static int TRACE_VAR = mainJNI.TRACE_VAR_get();

}
