/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

/**
 *  This class encapsulates an objective. It requires the direction (minimize or maximize), the variable to optimize, and the improvement step.
 */
public class OptimizeVar extends SearchMonitor {
  private transient long swigCPtr;

  protected OptimizeVar(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.OptimizeVar_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptimizeVar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_OptimizeVar(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptimizeVar(Solver s, boolean maximize, IntVar a, long step) {
    this(mainJNI.new_OptimizeVar(Solver.getCPtr(s), s, maximize, IntVar.getCPtr(a), a, step), true);
  }

  /**
   *  Returns the best value found during search.
   */
  public long best() {
    return mainJNI.OptimizeVar_best(swigCPtr, this);
  }

  /**
   *  Returns the variable that is optimized.
   */
  public IntVar var() {
    long cPtr = mainJNI.OptimizeVar_var(swigCPtr, this);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  /**
   *  Internal methods.
   */
  public boolean acceptDelta(Assignment delta, Assignment deltadelta) {
    return mainJNI.OptimizeVar_acceptDelta(swigCPtr, this, Assignment.getCPtr(delta), delta, Assignment.getCPtr(deltadelta), deltadelta);
  }

  public void enterSearch() {
    mainJNI.OptimizeVar_enterSearch(swigCPtr, this);
  }

  public void beginNextDecision(DecisionBuilder db) {
    mainJNI.OptimizeVar_beginNextDecision(swigCPtr, this, DecisionBuilder.getCPtr(db), db);
  }

  public void refuteDecision(Decision d) {
    mainJNI.OptimizeVar_refuteDecision(swigCPtr, this, Decision.getCPtr(d), d);
  }

  public boolean atSolution() {
    return mainJNI.OptimizeVar_atSolution(swigCPtr, this);
  }

  public boolean acceptSolution() {
    return mainJNI.OptimizeVar_acceptSolution(swigCPtr, this);
  }

  public String print() {
    return mainJNI.OptimizeVar_print(swigCPtr, this);
  }

  public String toString() {
    return mainJNI.OptimizeVar_toString(swigCPtr, this);
  }

  public void accept(ModelVisitor visitor) {
    mainJNI.OptimizeVar_accept(swigCPtr, this, ModelVisitor.getCPtr(visitor), visitor);
  }

  public void applyBound() {
    mainJNI.OptimizeVar_applyBound(swigCPtr, this);
  }

}
